# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hobit.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'hobit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhobit.proto\"\xcd\x04\n\tTransport\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x0e\n\x06\x62lk_no\x18\x02 \x02(\t\x12\x0e\n\x06press3\x18\x03 \x02(\x05\x12\x13\n\x0b\x63\x61lc_press2\x18\x04 \x02(\x02\x12\x0e\n\x06press4\x18\x05 \x02(\x05\x12\x13\n\x0b\x63\x61lc_press1\x18\x06 \x02(\x02\x12\x13\n\x0b\x63\x61lc_press4\x18\x07 \x02(\x02\x12\x13\n\x0b\x63\x61lc_press3\x18\x08 \x02(\x02\x12\x12\n\nbf_gps_lon\x18\t \x02(\x02\x12\x0f\n\x07gps_lat\x18\n \x02(\x02\x12\r\n\x05speed\x18\x0b \x02(\x02\x12\r\n\x05in_dt\x18\x0c \x02(\t\x12\x11\n\tmove_time\x18\r \x02(\x02\x12\x0e\n\x06\x64vc_id\x18\x0e \x02(\t\x12\x10\n\x08\x64sme_lat\x18\x0f \x02(\x02\x12\x0e\n\x06press1\x18\x10 \x02(\x05\x12\x0e\n\x06press2\x18\x11 \x02(\x05\x12\x13\n\x0bwork_status\x18\x12 \x02(\x05\x12\x11\n\ttimestamp\x18\x13 \x02(\t\x12\x11\n\tis_adjust\x18\x14 \x02(\t\x12\x15\n\rmove_distance\x18\x15 \x02(\x05\x12\x0e\n\x06weight\x18\x16 \x02(\x02\x12\x10\n\x08\x64sme_lon\x18\x17 \x02(\x02\x12\x0f\n\x07in_user\x18\x18 \x02(\t\x12\x0e\n\x06\x65qp_id\x18\x19 \x02(\x05\x12\x16\n\x0e\x62lk_get_seq_id\x18\x1a \x02(\x05\x12\x0e\n\x06lot_no\x18\x1b \x02(\t\x12\x0f\n\x07proj_no\x18\x1c \x02(\t\x12\x0f\n\x07gps_lon\x18\x1d \x02(\x02\x12\x0e\n\x06seq_id\x18\x1e \x02(\x05\x12\x12\n\nbf_gps_lat\x18  \x02(\x02\x12\x12\n\nblk_dvc_id\x18! \x02(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hobit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSPORT']._serialized_start=16
  _globals['_TRANSPORT']._serialized_end=605
# @@protoc_insertion_point(module_scope)
